language: python
before_script:
  - pip install tox
  # https://github.com/gabrielfalcao/HTTPretty/issues/242
  - pip install ndg-httpsclient==0.3.0

script: tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=flake8
